#!/bin/sh

# cd /
# mkdir -p installer-data
# cd installer-data
# tar xvf ../installer-data.tar.bz2
# rm -rf etc/systemd/system/dev-disk*
# rm -f etc/cloud/cloud.cfg
# cp -a etc/* /etc/
# cd ..
# rm -rf installer-data

cat <<EOF >/etc/default/console-setup

# CONFIGURATION FILE FOR SETUPCON

# Consult the console-setup(5) manual page.

ACTIVE_CONSOLES="/dev/tty[1-6]"

CHARMAP="UTF-8"

CODESET="guess"
FONTFACE="Fixed"
FONTSIZE="8x16"

VIDEOMODE=

# The following is an example how to use a braille font
# FONT='lat9w-08.psf.gz brl-8x8.psf'

EOF

/usr/bin/systemctl disable getty@tty1.service
/usr/bin/systemctl enable snap.subiquity.subiquity-server.service
/usr/bin/systemctl enable subiquity-launcher.service
/usr/bin/systemctl enable console-setup.service

mkdir -p /var/lib/cloud/seed/nocloud
touch /var/lib/cloud/seed/nocloud/meta-data
touch /var/lib/cloud/seed/nocloud/user-data

useradd ubuntu -p `mkpasswd --method=SHA-512 ubuntu` -s /bin/bash
hostname ubuntu
